### ISSUE TITLE
Generated changelog.

### ISSUE THREAD

**Issue by alejandronanez** [lerna/lerna-changelog#126]
Hello, first of all, thanks for creating this!

Question here, is that after running `yarn lerna-changelog` nothing is generated.

Is this expected? or am I missing something really obvious?

FWIW, this is what I get on my terminal.

```sh
yarn run v1.10.1
$ /Users/x/x/x/node_modules/.bin/lerna-changelog

## Unreleased (2018-11-10)

#### :bug: Bug Fix
* `package-name-X`, `theme`
  * [#202](github url) change ([@author](https://github.com/author))

#### Committers: 1
- Author ([@author](https://github.com/author))
```

Happy to provide more info if needed, 

thanks!

**Comment by emmenko** [comment]
That's correct, you get the changelog printed in the terminal output. You then copy-paste it into your `CHANGELOG.md` and/or GitHub Releases.

**Comment by alejandronanez** [comment]
Gotcha.

Is there a way to automate this process? I know this is out of the scope of this project but some advice would help me :)

Thanks again! :)

**Comment by emmenko** [comment]
Well, it depends on your release process. But you could e.g. run the script on CI before a release and pipe the output to the `CHANGELOG.md`.

However, I would personally not recommend to automate it because often times you want to tweak it and to add more useful information. The manual step really takes little time and it’s much more safe.

**Comment by alejandronanez** [comment]
That’s what I thought @emmenko, thanks for your response.

Will close since this behavior is expected.
